---
title: "Final Project BST 260: The Effects of Pesticide Exposure on Maternal and Child Health (Lara, Sonia, Zainab)"
output: html_document
---
Load Packages
```{r}
library(dplyr)
library(tidyverse)
library(pdftools)
library(readr)
library(stringr)

```

Load Datasets
```{r}

```

MCH Data Wrangling *Low BW Only
```{r}
#Data Wrangling for Year 2014-2018 Data 
lbwdata<- read.csv("low-and-very-low-birthweight-by-county-2014-2018 (1).csv", header = TRUE, stringsAsFactors = FALSE)
lbwdata$Events[is.na(lbwdata$Events)] <- 0
lbwdata <- lbwdata %>% group_by(Year, County, Total.Births) %>% summarize(Events = sum(Events)) 
lbwdata <- lbwdata %>% filter(!County == "california")#removing the total count
lbwdata <- lbwdata %>% mutate(rate = Events/Total.Births * 100)
``` 

MCH Data Wrangling *New CDC Data (Lara)
```{r}
#Data Wrangling for CDC Data (COMPLETE)
``` 

Pesticide Data Wrangling

```{r}
county_ranks16 <- read_delim("table1_county_rank_2016.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
repro_lbs16 <- read_delim("table3_reproductive_lbs_2016.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
repro_acre16 <- read_delim("table4_reproductive_acres_2016.txt", "\t", escape_double = FALSE, trim_ws = TRUE)


table1_2016 <- county_ranks16 %>% transmute(county = COUNTY, 
                                     lbs_2015 = LBS_2015, rank_2015 = RANK_2015, 
                                     lbs_2016 = LBS_2016, rank_2016 = RANK_2016)
# column 1 is the county
# columns 2-3 have the previous year data
# columns 4-5 have the current year data

# we only want columns 1-3 for the most up-to-date data for all years before 2016
all_dat <- list(read_csv("table1_2007.csv")[1:3],
                read_csv("table1_2008.csv")[1:3],
                read_csv("table1_2009.csv")[1:3],
                read_csv("table1_2010.csv")[1:3],
                read_csv("table1_2011.csv")[1:3],
                read_csv("table1_2012.csv")[1:3],
                read_csv("table1_2013.csv")[1:3],
                read_csv("table1_2014.csv")[1:3],
                read_csv("table1_2015.csv")[1:3])


table1 <- Reduce(function(x, y) left_join(x, y, by = "county"), all_dat)


long_table1 <- table1 %>% pivot_longer(!county, names_to = 'usage', values_to = "value")
table1_ranks <- long_table1 %>% filter(str_starts(usage, "rank"))
table1_lbs <- long_table1 %>% filter(str_starts(usage, "lbs"))
```

Sonia's Work with LBW Data
```{r}
#Histogram by county  
lbwdata %>% 
  filter(Year == 2014 & !is.na(rate)) %>% 
  ggplot(aes(County, rate)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1/2))
 
#Heatmap 
library(maps)
CaliforniaCounty <- map_data("county", "california")
head(CaliforniaCounty)

CaliforniaCounty %>% ggplot(aes(x = long, y = lat, group = group)) + 
                  geom_polygon(fill = "white", color = "black") +
                  theme(panel.grid.major = element_blank(), 
                        panel.background = element_blank(),
                        axis.title = element_blank(), 
                        axis.text = element_blank(),
                        axis.ticks = element_blank()) +
                  coord_fixed(1.3)

california_map <- lbwdata %>% full_join(CaliforniaCounty, by = c("County" = "subregion")) %>% mutate(rate = Events/Total.Births * 10^2)

#see Sonia's app for the shiny app 
```

